Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2018-09, with the labels that each got.

#30 vend in azureRM suppress and validate packages
  azurestack/helpers/suppress/string_test.go
  azurestack/helpers/suppress/time_test.go
  azurestack/helpers/validate/network_test.go
  azurestack/helpers/validate/time_test.go
  azurestack/resource_arm_loadbalancer.go
  azurestack/resource_arm_loadbalancer_nat_pool.go
  azurestack/resource_arm_loadbalancer_nat_rule.go
  azurestack/resource_arm_loadbalancer_rule.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/LICENSE
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/suppress/string.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/suppress/time.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate/network.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate/time.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate/url.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate/uuid.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate/validate.go
  vendor/vendor.json
Labels: technical-debt

#29 remove separate import tests
  azurestack/import_arm_availability_set_test.go
  azurestack/import_arm_local_network_gateway_test.go
  azurestack/import_arm_network_interface_test.go
  azurestack/import_arm_network_security_group_test.go
  azurestack/import_arm_public_ip_test.go
  azurestack/import_arm_resource_group_test.go
  azurestack/import_arm_security_rule_test.go
  azurestack/import_arm_storage_account_test.go
  azurestack/import_arm_subnet_test.go
  azurestack/import_arm_virtual_machine_test.go
  azurestack/import_arm_virtual_network_test.go
  azurestack/resource_arm_availability_set_test.go
  azurestack/resource_arm_local_network_gateway_test.go
  azurestack/resource_arm_network_interface_test.go
  azurestack/resource_arm_network_security_group_test.go
  azurestack/resource_arm_network_security_rule_test.go
  azurestack/resource_arm_public_ip_test.go
  azurestack/resource_arm_resource_group_test.go
  azurestack/resource_arm_storage_account_test.go
  azurestack/resource_arm_subnet_test.go
  azurestack/resource_arm_virtual_machine_unmanaged_disks_test.go
  azurestack/resource_arm_virtual_network_test.go
Labels: size/XXL, technical-debt

#33 Template deployment resource
  azurestack/config.go
  azurestack/provider.go
  azurestack/resource_arm_template_deployment.go
  azurestack/resource_arm_template_deployment_test.go
  website/azurestack.erb
  website/docs/r/template_deployment.html.markdown
Labels: size/XXL

#31 Virtual network gateway
  azurestack/config.go
  azurestack/data_source_virtual_network_gateway.go
  azurestack/data_source_virtual_network_gateway_test.go
  azurestack/provider.go
  azurestack/resource_arm_virtual_network_gateway.go
  azurestack/resource_arm_virtual_network_gateway_test.go
  azurestack/test_utils.go
  vendor/github.com/satori/uuid/LICENSE
  vendor/github.com/satori/uuid/README.md
  vendor/github.com/satori/uuid/codec.go
  vendor/github.com/satori/uuid/generator.go
  vendor/github.com/satori/uuid/sql.go
  vendor/github.com/satori/uuid/uuid.go
  website/azurestack.erb
  website/docs/d/virtual_network_gateway.html.markdown
  website/docs/r/virtual_network_gateway.html.markdown
Labels: size/XXL, waiting-response

#34 Add subnet and public ip data source
  azurestack/data_source_public_ip.go
  azurestack/data_source_public_ip_test.go
  azurestack/data_source_subnet.go
  azurestack/data_source_subnet_test.go
  azurestack/provider.go
  website/docs/d/public_ip.html.markdown
  website/docs/d/subnet.html.markdown
Labels: size/XL, waiting-response

#36 Minor fix to virtual network gateway validation
  azurestack/resource_arm_virtual_network_gateway.go
Labels: bug, size/XS

#35 Virtual network gateway connection
  azurestack/config.go
  azurestack/provider.go
  azurestack/provider_test.go
  azurestack/resource_arm_virtual_network_gateway_connection.go
  azurestack/resource_arm_virtual_network_gateway_connection_test.go
  website/docs/r/virtual_network_gateway_connection.html.markdown
Labels: new-resource, size/XXL

#15 AzureStack Scale set Resource
  azurestack/config.go
  azurestack/helpers/azure/resourceid.go
  azurestack/helpers/azure/validate.go
  azurestack/helpers/azure/validate_test.go
  azurestack/provider.go
  azurestack/resource_arm_loadbalancer.go
  azurestack/resource_arm_loadbalancer_probe.go
  azurestack/resource_arm_loadbalancer_rule.go
  azurestack/resource_arm_virtual_machine_scale_set.go
  azurestack/resource_arm_virtual_machine_scale_set_test.go
  azurestack/resource_arm_virtual_network_gateway_connection.go
  vendor/github.com/Azure/azure-sdk-for-go/LICENSE
  vendor/github.com/Azure/azure-sdk-for-go/NOTICE
  website/azurestack.erb
  website/docs/r/virtual_machine_scale_set.html.markdown
Labels: size/XXL, waiting-response

#40 Remove grocer's apostrophe
  website/docs/r/virtual_network.html.markdown
Labels: size/XS

#42 azurestack_public_ip: correct import & read idle_timeout_in_minutes
  azurestack/resource_arm_public_ip.go
  azurestack/resource_arm_public_ip_test.go
  azurestack/resource_arm_route_table.go
  azurestack/resource_arm_virtual_network_gateway.go
  azurestack/resource_arm_virtual_network_gateway_connection.go
Labels: bug, size/L

#41 Switch to GoMetaLinter and enable errcheck, interfacer, and structcheck linting in TravisCI
  .gometalinter.json
  .travis.yml
  GNUmakefile
  azurestack/config.go
  azurestack/resource_arm_storage_blob.go
  azurestack/resource_arm_virtual_machine_scale_set_test.go
  azurestack/resource_arm_virtual_machine_unmanaged_disks_test.go
  scripts/errcheck.sh
Labels: provider, size/M, technical-debt

#48 azurestack.erb update
  website/azurestack.erb
Labels: documentation, size/XS

#46 Switch response and utils packages to azurerm versions
  azurestack/config.go
  azurestack/data_source_network_interface.go
  azurestack/data_source_network_security_group.go
  azurestack/data_source_public_ip.go
  azurestack/data_source_route_table.go
  azurestack/data_source_storage_account.go
  azurestack/data_source_subnet.go
  azurestack/data_source_virtual_network.go
  azurestack/data_source_virtual_network_gateway.go
  azurestack/helpers/response/response_test.go
  azurestack/resource_arm_availability_set.go
  azurestack/resource_arm_availability_set_test.go
  azurestack/resource_arm_dns_a_record.go
  azurestack/resource_arm_dns_zone.go
  azurestack/resource_arm_loadbalancer.go
  azurestack/resource_arm_loadbalancer_backend_address_pool.go
  azurestack/resource_arm_loadbalancer_nat_pool.go
  azurestack/resource_arm_loadbalancer_nat_rule.go
  azurestack/resource_arm_loadbalancer_probe.go
  azurestack/resource_arm_loadbalancer_rule.go
  azurestack/resource_arm_local_network_gateway.go
  azurestack/resource_arm_local_network_gateway_test.go
  azurestack/resource_arm_network_interface.go
  azurestack/resource_arm_network_interface_test.go
  azurestack/resource_arm_network_security_group.go
  azurestack/resource_arm_network_security_group_test.go
  azurestack/resource_arm_network_security_rule.go
  azurestack/resource_arm_network_security_rule_test.go
  azurestack/resource_arm_public_ip.go
  azurestack/resource_arm_resource_group.go
  azurestack/resource_arm_resource_group_test.go
  azurestack/resource_arm_route.go
  azurestack/resource_arm_route_table.go
  azurestack/resource_arm_route_table_test.go
  azurestack/resource_arm_route_test.go
  azurestack/resource_arm_storage_account.go
  azurestack/resource_arm_subnet.go
  azurestack/resource_arm_subnet_test.go
  azurestack/resource_arm_template_deployment.go
  azurestack/resource_arm_virtual_machine.go
  azurestack/resource_arm_virtual_machine_extension.go
  azurestack/resource_arm_virtual_machine_scale_set.go
  azurestack/resource_arm_virtual_network.go
  azurestack/resource_arm_virtual_network_gateway.go
  azurestack/resource_arm_virtual_network_gateway_connection.go
  azurestack/resource_arm_virtual_network_gateway_connection_test.go
  azurestack/resource_arm_virtual_network_gateway_test.go
  azurestack/resource_arm_virtual_network_test.go
  azurestack/utils/response_test.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/response/response.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/validate/virtual_network_rule_name.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils/response.go
  vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils/utils.go
  vendor/vendor.json
Labels: size/L, technical-debt
