Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2018-12, with the labels that each got.

#59 Upgrading to 0.3.1 of github.com/hashicorp/go-azure-helpers
  vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_azure_cli_parsing.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_azure_cli_token.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/azure_cli_access_token.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/azure_cli_profile.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/azure_cli_profile_population.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/builder.go
  vendor/vendor.json
Labels: dependencies, enhancement, size/XL

#58 Documentation virtual network gateway
  website/azurestack.erb
  website/docs/r/virtual_network_gateway.html.markdown
Labels: documentation, size/L

#62 Small change to arg ref documentation
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#56 authentication: support for Client Certificate authentication
  azurestack/provider.go
  website/azurestack.erb
  website/docs/auth/service_principal_client_certificate.html.markdown
  website/docs/auth/service_principal_client_secret.html.markdown
  website/docs/index.html.markdown
Labels: enhancement, size/XL
