Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2019-04, with the labels that each got.

#57 authentication: support for the Azure CLI
  azurestack/provider.go
  go.mod
  go.sum
  vendor/modules.txt
  website/azurestack.erb
  website/docs/auth/azure_cli.html.markdown
  website/docs/auth/service_principal_client_certificate.html.markdown
  website/docs/auth/service_principal_client_secret.html.markdown
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/M

#78 Update terraform to v0.11.13
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform/config/interpolate_funcs.go
  vendor/github.com/hashicorp/terraform/config/module/get.go
  vendor/github.com/hashicorp/terraform/config/module/storage.go
  vendor/github.com/hashicorp/terraform/config/module/validate_provider_alias.go
  vendor/github.com/hashicorp/terraform/helper/logging/transport.go
  vendor/github.com/hashicorp/terraform/helper/resource/id.go
  vendor/github.com/hashicorp/terraform/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform/helper/resource/testing_config.go
  vendor/github.com/hashicorp/terraform/helper/resource/wait.go
  vendor/github.com/hashicorp/terraform/helper/schema/data_source_resource_shim.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_map.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go
  vendor/github.com/hashicorp/terraform/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform/helper/schema/set.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/github.com/hashicorp/terraform/httpclient/client.go
  vendor/github.com/hashicorp/terraform/httpclient/useragent.go
  vendor/github.com/hashicorp/terraform/plugin/discovery/get.go
  vendor/github.com/hashicorp/terraform/plugin/ui_input.go
  vendor/github.com/hashicorp/terraform/registry/client.go
  vendor/github.com/hashicorp/terraform/registry/errors.go
  vendor/github.com/hashicorp/terraform/svchost/auth/credentials.go
  vendor/github.com/hashicorp/terraform/svchost/auth/token_credentials.go
  vendor/github.com/hashicorp/terraform/svchost/disco/disco.go
  vendor/github.com/hashicorp/terraform/svchost/disco/host.go
  vendor/github.com/hashicorp/terraform/terraform/context.go
  vendor/github.com/hashicorp/terraform/terraform/eval_apply.go
  vendor/github.com/hashicorp/terraform/terraform/eval_validate.go
  vendor/github.com/hashicorp/terraform/terraform/graph_builder_apply.go
  vendor/github.com/hashicorp/terraform/terraform/interpolate.go
  vendor/github.com/hashicorp/terraform/terraform/node_local.go
  vendor/github.com/hashicorp/terraform/terraform/node_output.go
  vendor/github.com/hashicorp/terraform/terraform/node_resource_apply.go
  vendor/github.com/hashicorp/terraform/terraform/node_resource_refresh.go
  vendor/github.com/hashicorp/terraform/terraform/state.go
  vendor/github.com/hashicorp/terraform/terraform/test_failure
  vendor/github.com/hashicorp/terraform/terraform/transform_output.go
  vendor/github.com/hashicorp/terraform/terraform/transform_reference.go
  vendor/github.com/hashicorp/terraform/terraform/transform_targets.go
  vendor/github.com/hashicorp/terraform/terraform/ui_input.go
  vendor/github.com/hashicorp/terraform/terraform/ui_input_mock.go
  vendor/github.com/hashicorp/terraform/terraform/ui_input_prefix.go
  vendor/github.com/hashicorp/terraform/terraform/user_agent.go
  vendor/github.com/hashicorp/terraform/version/version.go
  vendor/github.com/jmespath/go-jmespath/.gitignore
  vendor/modules.txt
Labels: bug, dependencies, size/XXL

#79 Update test storage_image_reference from 2012 -> 2016
  azurestack/resource_arm_virtual_machine_unmanaged_disks_test.go
Labels: bug, size/XS
