Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2019-03, with the labels that each got.

#73 website: Update link to `file` function
  website/docs/r/template_deployment.html.markdown
Labels: documentation, size/XS

#72 azurestack_dns_zone: switch record count schema from a string to an int
  azurestack/resource_arm_dns_zone.go
Labels: bug, size/XS

#71 azurestack_virtual_network_gateway: fix panic if bgp_settings is set with 0 elements
  azurestack/resource_arm_virtual_network_gateway.go
Labels: bug, size/XS

#74 DataSource: azurestack_storage_account - do not try and set account_kind
  azurestack/data_source_storage_account.go
  azurestack/resource_arm_loadbalancer_probe.go
Labels: bug, size/XS

#76 Format terraform test blocks
  azurestack/data_source_network_interface_test.go
  azurestack/data_source_storage_account_test.go
  azurestack/data_source_virtual_network_gateway_test.go
  azurestack/data_source_virtual_network_test.go
  azurestack/resource_arm_dns_zone_test.go
  azurestack/resource_arm_loadbalancer_backend_address_pool_test.go
  azurestack/resource_arm_loadbalancer_nat_pool_test.go
  azurestack/resource_arm_loadbalancer_probe_test.go
  azurestack/resource_arm_loadbalancer_rule_test.go
  azurestack/resource_arm_loadbalancer_test.go
  azurestack/resource_arm_local_network_gateway_test.go
  azurestack/resource_arm_network_interface_test.go
  azurestack/resource_arm_network_security_group_test.go
  azurestack/resource_arm_network_security_rule_test.go
  azurestack/resource_arm_public_ip_test.go
  azurestack/resource_arm_resource_group_test.go
  azurestack/resource_arm_route_table_test.go
  azurestack/resource_arm_route_test.go
  azurestack/resource_arm_storage_account_test.go
  azurestack/resource_arm_storage_blob_test.go
  azurestack/resource_arm_storage_cointainer_test.go
  azurestack/resource_arm_subnet_test.go
  azurestack/resource_arm_template_deployment_test.go
  azurestack/resource_arm_virtual_machine_extension_test.go
  azurestack/resource_arm_virtual_machine_scale_set_test.go
  azurestack/resource_arm_virtual_machine_unmanaged_disks_test.go
  azurestack/resource_arm_virtual_network_gateway_connection_test.go
  azurestack/resource_arm_virtual_network_gateway_test.go
  azurestack/resource_arm_virtual_network_test.go
Labels: refactor, size/XXL, technical-debt
