Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2019-01, with the labels that each got.

#65 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
Labels: size/XS

#66 cross-linking between the different azure providers
  website/azurestack.erb
Labels: documentation, size/XS

#68 linting: update to use new staticcheck
  .gometalinter.json
  azurestack/provider.go
  staticcheck.conf
Labels: refactor, size/XS
