Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2022-04, with the labels that each got.

#173 Removed some unsupported tests, modified the validation for Virtual Network Gateway Connection
  internal/services/network/virtual_network_gateway_connection_resource.go
  internal/services/network/virtual_network_gateway_connection_resource_test.go
  website/docs/r/virtual_network_gateway_connection.html.markdown
Labels: size/XL, documentation

#143 Use custom-built images for booting up VMs
  internal/services/compute/client/client.go
  internal/services/compute/image_data_source.go
  internal/services/compute/image_data_source_test.go
  internal/services/compute/image_resource.go
  internal/services/compute/image_resource_test.go
  internal/services/compute/registration.go
  website/docs/d/image.html.markdown
  website/docs/r/image.html.markdown
Labels: size/XL, documentation

#175 Removed unsupported parameters, added new parameters and more for Managed Disk
  internal/services/compute/encryption_settings.go
  internal/services/compute/managed_disk_data_source.go
  internal/services/compute/managed_disk_data_source_test.go
  internal/services/compute/managed_disk_resource.go
  internal/services/compute/managed_disk_resource_test.go
  website/docs/d/managed_disk.html.markdown
  website/docs/r/managed_disk.html.markdown
Labels: size/XL, documentation

#176 Fixes the tests for Virtual Machine using Multiple NICs
  internal/services/compute/linux_virtual_machine_resource_network_test.go
Labels: size/M

#178 Fixes various tests of network
  internal/services/network/loadbalancer_backend_address_pool_association_resource.go
  internal/services/network/public_ips_data_source_test.go
  internal/services/network/virtual_network_gateway_connection_data_source_test.go
Labels: size/L

#179 Fixes a test of authorization
  internal/services/authorization/client_config_data_source_test.go
Labels: size/XS

#180 Fixes tests of loadbalancer
  internal/services/loadbalancer/loadbalancer_data_source_test.go
  internal/services/loadbalancer/loadbalancer_nat_pool_resource_test.go
  internal/services/loadbalancer/loadbalancer_nat_rule_resource_test.go
  internal/services/loadbalancer/loadbalancer_rule_data_source_test.go
Labels: size/M

#181 Fixes two tests of template deployment
  internal/services/resource/resource_arm_template_deployment_test.go
Labels: size/XS

#183 Fix tests
  internal/services/compute/platform_image_data_source_test.go
  internal/services/compute/virtual_machine_data_disk_attachment_resource_test.go
  internal/services/loadbalancer/loadbalancer_backend_address_pool_resource_test.go
  internal/services/loadbalancer/loadbalancer_rule_resource_test.go
  internal/services/network/public_ip_resource_test.go
  internal/services/resource/resource_arm_template_deployment_test.go
Labels: size/XS

#184 Fix auth objectid
  internal/clients/auth.go
  internal/provider/provider.go
  internal/services/authorization/client_config_data_source_test.go
Labels: size/S

#182 New resources for Linux and Windows Virtual Machine Scale Set
  internal/features/defaults.go
  internal/features/user_flags.go
  internal/provider/features.go
  internal/provider/features_test.go
  internal/services/compute/helpers.go
  internal/services/compute/linux_virtual_machine_scale_set_auth_resource_test.go
  internal/services/compute/linux_virtual_machine_scale_set_disk_data_resource_test.go
  internal/services/compute/linux_virtual_machine_scale_set_disk_os_resource_test.go
  internal/services/compute/linux_virtual_machine_scale_set_extensions_test.go
  internal/services/compute/linux_virtual_machine_scale_set_network_resource_test.go
  internal/services/compute/linux_virtual_machine_scale_set_resource.go
  internal/services/compute/linux_virtual_machine_scale_set_resource_test.go
  internal/services/compute/registration.go
  internal/services/compute/virtual_machine_resource_t_unmanaged_disks_resource_test.go
  internal/services/compute/virtual_machine_scale_set.go
  internal/services/compute/virtual_machine_scale_set_import.go
  internal/services/compute/virtual_machine_scale_set_resource.go
  internal/services/compute/virtual_machine_scale_set_update.go
  internal/services/compute/windows_virtual_machine_scale_set_auth_resource_test.go
  internal/services/compute/windows_virtual_machine_scale_set_disk_data_resource_test.go
  internal/services/compute/windows_virtual_machine_scale_set_disk_os_resource_test.go
  internal/services/compute/windows_virtual_machine_scale_set_extensions_test.go
  internal/services/compute/windows_virtual_machine_scale_set_network_resource_test.go
  internal/services/compute/windows_virtual_machine_scale_set_resource.go
  internal/services/compute/windows_virtual_machine_scale_set_resource_test.go
  website/docs/r/linux_virtual_machine_scale_set.html.markdown
  website/docs/r/windows_virtual_machine_scale_set.html.markdown
Labels: size/XL, documentation
