Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2022-07, with the labels that each got.

#188 1.0 changelog + guides + misc docs fixes
  CHANGELOG-v0.md
  CHANGELOG.md
  website/docs/guides/1.0-upgrade-guide.html.markdown
  website/docs/guides/features-block.html.markdown
  website/docs/index.html.markdown
  website/docs/r/loadbalancer.html.markdown
  website/docs/r/storage_account.html.markdown
Labels: size/XL, documentation

#192 Deprecate the `arm_endpoint` provider property
  go.mod
  go.sum
  internal/provider/provider.go
  internal/tf/acceptance/data.go
  internal/tf/acceptance/testing.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/environment.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: size/M, dependencies, documentation

#193 update guide with metadata_hostname change
  .teamcity/components/build_azure.kt
  README.md
  internal/provider/provider.go
  internal/tf/acceptance/data.go
  internal/tf/acceptance/testclient/client.go
  internal/tf/acceptance/testing.go
  website/docs/guides/1.0-upgrade-guide.html.markdown
  website/docs/guides/azure_cli.html.markdown
  website/docs/guides/service_principal_client_certificate.html.markdown
  website/docs/guides/service_principal_client_secret.html.markdown
  website/docs/index.html.markdown
Labels: size/M, documentation

#194 final 1.0 updates
  CHANGELOG.md
  internal/services/keyvault/key_vault_key_resource.go
  internal/services/keyvault/key_vault_secret_resource.go
  scripts/release.sh
  website/docs/d/local_network_gateway.html.markdown
  website/docs/d/resources.html.markdown
  website/docs/guides/1.0-upgrade-guide.html.markdown
Labels: size/M, documentation
