Repository hashicorp/terraform-provider-azurestack, pull requests merged in 2022-03, with the labels that each got.

#162 Removed unsupported parameters for Virtual Network Gateway
  internal/services/network/virtual_network_gateway_data_source.go
  internal/services/network/virtual_network_gateway_resource.go
  internal/services/network/virtual_network_gateway_resource_test.go
  website/docs/r/virtual_network_gateway.html.markdown
Labels: size/XL, documentation

#147 Add virtual network peering
  internal/services/network/client/client.go
  internal/services/network/parse/virtual_network_peering.go
  internal/services/network/parse/virtual_network_peering_test.go
  internal/services/network/registration.go
  internal/services/network/resourceids.go
  internal/services/network/validate/virtual_network_peering_id.go
  internal/services/network/validate/virtual_network_peering_id_test.go
  internal/services/network/virtual_network_peering_resource.go
  internal/services/network/virtual_network_peering_resource_test.go
  website/docs/r/virtual_network_peering.html.markdown
Labels: size/XL, documentation

#160 Removed unsupported parameters in network security group resource/datasource
  internal/services/network/network_security_group_data_source.go
  internal/services/network/network_security_group_resource.go
  internal/services/network/network_security_group_resource_test.go
Labels: size/M

#155 Adding azurestack_network_interface_backend_address_pool_association …
  internal/services/network/loadbalancer_backend_address_pool_association_resource.go
  internal/services/network/loadbalancer_backend_address_pool_association_resource_test.go
  internal/services/network/network_interface_helpers.go
  internal/services/network/parse/network_interface_ip_configuration.go
  internal/services/network/parse/network_interface_ip_configuration_test.go
  internal/services/network/registration.go
  website/docs/r/network_interface_backend_address_pool_association.html.markdown
  website/docs/r/virtual_network_peering.html.markdown
Labels: size/XL, documentation

#158 Refactor in public ip resource and datasource
  internal/services/network/public_ip_resource.go
  internal/services/network/public_ip_resource_test.go
  website/docs/d/public_ip.html.markdown
  website/docs/r/public_ip.html.markdown
Labels: size/M, documentation

#165 Updated Local network gateway resource
  internal/services/network/local_network_gateway_data_source.go
  website/docs/d/local_network_gateway.html.markdown
  website/docs/r/local_network_gateway.html.markdown
Labels: size/M, documentation

#161 Removed unsupported parameters in network security rule resource/datasource
  internal/services/network/application_security_group_data_source.go
  internal/services/network/application_security_group_data_source_test.go
  internal/services/network/application_security_group_resource.go
  internal/services/network/application_security_group_resource_test.go
  internal/services/network/network_security_rule_resource.go
  internal/services/network/network_security_rule_resource_test.go
  internal/services/network/registration.go
Labels: size/XL

#167 Updated subnet datasource
  internal/services/network/subnet_data_source.go
  internal/services/network/subnet_data_source_test.go
  website/docs/d/subnet.html.markdown
Labels: size/M, documentation

#164 Updated network interface resource and datasource
  internal/services/network/network_interface_data_source.go
  internal/services/network/network_interface_resource.go
  internal/services/network/network_interface_resource_test.go
  website/docs/r/network_interface.html.markdown
Labels: size/L, documentation

#166 Updated profile for ARM Template Deployment
  internal/az/resourceproviders/registration.go
  internal/services/resource/client/client.go
  internal/services/resource/resource_arm_template_deployment.go
  internal/services/resource/resource_arm_template_deployment_test.go
  internal/services/resource/resource_group_resource.go
  internal/tf/acceptance/required_test.go
  vendor/github.com/Azure/azure-sdk-for-go/profiles/2020-09-01/resources/mgmt/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/deploymentoperations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/deployments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/groups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/providers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/resources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/tags.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/version.go
  vendor/github.com/hashicorp/go-azure-helpers/resourceproviders/registration.go
  vendor/modules.txt
Labels: size/XL, dependencies

#168 Updated virtual network datasource
  internal/services/network/virtual_network_data_source_test.go
  website/docs/d/virtual_network.html.markdown
Labels: size/M, documentation

#170 Added Resources data source
  internal/services/resource/registration.go
  internal/services/resource/resources_data_source.go
  internal/services/resource/resources_data_source_test.go
  website/docs/d/resources.html.markdown
Labels: size/XL, documentation

#163 Storage blob support
  internal/services/storage/blobs.go
  internal/services/storage/storage_blob_resource.go
  internal/services/storage/storage_blob_resource_test.go
  internal/services/storage/validate/metadata_keys_test.go
  website/docs/r/storage_blob.html.markdown
Labels: size/XL, documentation

#152 Added a parameters for LoadBalancer resource
  internal/services/loadbalancer/loadbalancer_resource.go
  internal/services/loadbalancer/loadbalancer_resource_test.go
  website/docs/r/loadbalancer.html.markdown
Labels: size/XS, documentation

#169 Updated Storage account
  internal/services/storage/storage_account_data_source.go
  internal/services/storage/storage_account_resource.go
  internal/services/storage/storage_account_resource_test.go
  internal/services/storage/validate/storage_account_tags.go
  website/docs/d/storage_account.html.markdown
  website/docs/r/storage_account.html.markdown
Labels: size/L, documentation

#171 Fixes various tests of Virtual Machine Scale Set and some for Virtual Machine Unmanaged disks
  internal/services/compute/virtual_machine_resource_t_managed_disks_resource_test.go
  internal/services/compute/virtual_machine_resource_t_unmanaged_disks_resource_test.go
  internal/services/compute/virtual_machine_scale_set_resource.go
  internal/services/compute/virtual_machine_scale_set_resource_test.go
  website/docs/r/virtual_machine_scale_set.html.markdown
Labels: size/XL, documentation

#174 Removed one test of Virtual Machine Extension
  internal/services/compute/virtual_machine_extension_resource_test.go
Labels: size/M
